site_name: Choco
site_description: A simple and comfortable programming language made for developers.
site_author: Camila "Mocha" Rose (CoffeeShop Development)
repo_url: https://github.com/mochacinno-dev/ChocoLang
repo_name: mochacinno-dev/ChocoLang

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - ruby
    - rust
    - go
    - bash

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
